#----------------------------------------------------------------------------
#          _    _           Family:    aRVern System IPs
#         / \__/ \          Module:    vc_lint.tcl
#        /   /\   \         --------------------------------------------
#    ===/   /=========      Copyright: (c) 2026, aRVern-dev
#      /   / RV \   \       Contact:   arvernsilicon@gmail.com
#     /___/______\___\      GitHub:    https://github.com/Arvern-Silicon
#
# SPDX-License-Identifier: BSD-3-Clause
# Full license text is available in the LICENSE file at the repository root.
#----------------------------------------------------------------------------
# File Name          : vc_lint.tcl
# Module Description : VC Static (vcst) lint script for arvern_fpga -- read, elaborate, check, report.
#----------------------------------------------------------------------------
# Invoked by run_vclint from inside ./results/, so every relative path here is
# results-relative and all vcst scratch (WORK/, vcst_rtdb/, clog*, novas.*)
# stays inside the gitignored output dir.
#
# Structurally identical to arvern/lint/vc_static/vc_lint.tcl. The one
# difference follows from linting a board-level SoC rather than a core: the
# top's parameters are fixed in arvern_fpga.v, so there is no elaboration
# override; rtl_params.tcl carries only the RTL_PARAM_* values that rules.tcl
# and waivers.tcl branch on, harvested from the RTL itself.

set TOP         $::env(VCLINT_TOP)
set FILELIST    $::env(VCLINT_FILELIST)
set STAGES      $::env(VCLINT_STAGES)
set JOBS        $::env(VCLINT_JOBS)
set RULES       $::env(VCLINT_RULES)
set WAIVERS     $::env(VCLINT_WAIVERS)
set DO_LANG     $::env(VCLINT_DO_LANG)
set PARAMS_FILE $::env(VCLINT_PARAMS_FILE)

# rtl_params.tcl is generated by run_vclint by reading the parameter
# declarations out of the top-level RTL, so the rule policy always sees the
# configuration that is actually being linted. That is load-bearing here:
# arvern_fpga.v builds with ASYNC_RST_EN=0, and the two reset rules are mutually
# exclusive -- without this the run would enforce the asynchronous rule on a
# fully synchronous design and flag every flop. Defines RTL_PARAM_<NAME> only;
# there is no ELABORATE_PARAMS here.
if {$PARAMS_FILE ne "" && [file exists $PARAMS_FILE]} {
    source $PARAMS_FILE
}

set search_path "."
set link_library " "
set enable_lang_checker true
set synth_preserve_sequential true
set_app_var analyze_skip_translate_body false
compress_hdl -enable

configure_hdl_tag -clear
configure_hdl_tag -enable -stage $STAGES

if {$RULES ne "" && [file exists $RULES]} {
    puts "\[vc_lint\] applying rule policy: $RULES"
    source $RULES
} else {
    puts "\[vc_lint\] RAW MODE -- no rule policy applied (all enabled stages active)"
}

define_design_lib WORK -path ./WORK
# The leading/trailing spaces matter: without them vcst parses the string as a
# command option and errors with "unknown option '-f ...'".
analyze -format verilog " -f $FILELIST "

elaborate $TOP
current_design $TOP

if {$DO_LANG eq "1"} {
    check_hdl -lang -structure -j $JOBS
} else {
    check_hdl -structure
}

# Waivers MUST come after check_hdl: waive_hdl filters the violation database,
# so applying it earlier silently matches nothing.
if {$WAIVERS ne "" && [file exists $WAIVERS]} {
    puts "\[vc_lint\] applying waivers: $WAIVERS"
    source $WAIVERS
    puts "\[vc_lint\] waivers that matched nothing:"
    catch {waive_hdl -not_applied}
}

report_hdl -file ./report.lint_summary.txt
report_hdl -file ./report.lint_full.txt    -verbose -sort
# -only_waived and -include_waived are mutually exclusive; -only_waived alone
# is what produces the waived-items report.
report_hdl -file ./report.lint_waived.txt  -only_waived -verbose -gen_empty

foreach fam {CLK RST CONN CODING NAMING SIM SIMSYN SVSYN SYN XPROP} {
    report_hdl -file ./report.lint_by_family.txt -append -family $fam -list -gen_empty
}

quit
