##############################################################################
#                                                                            #
#                               READ DESING RTL                              #
#                                                                            #
##############################################################################

set DESIGN_NAME      "chip_example"

# RTL_SOURCE_FILES (+ RTL_INCDIRS) come from submit_syn.tcl, auto-generated by
# `flatten_filelist.py --format tcl` (in run_syn) from the single-source design
# filelist rtl/verilog/filelist.f. This replaces the formerly hand-maintained
# inline list, which had drifted (e.g. missing arv_dff.v / arv_ipdff.v).
source ./submit_syn.tcl

if {[info exists  ::env(FABRIC_TYPE)]} {
    set AHB_TYPE $::env(FABRIC_TYPE)
}

set_svf ./results/$DESIGN_NAME.svf
define_design_lib WORK -path ./WORK
analyze -format verilog -define $AHB_TYPE [concat $RTL_SOURCE_FILES $SRAM_VERILOG_WRAPPER]

elaborate $DESIGN_NAME
link


# Check design structure after reading verilog
current_design $DESIGN_NAME
redirect ./results/report.check {check_design}
